### ISSUE TITLE
Centering the map

### ISSUE THREAD

**Issue by lucymk** [fac-17/Generation-Change#112]
I only had a super quick look at this, but I used leaflet on a FAC project and this was the set up page: https://github.com/fac-12/upShop/blob/master/public/map.js

it's not in React, but hopefully still useful. 

I think setView is the important function?! https://leafletjs.com/reference-1.5.0.html

This is only a little thing to go on, but hopefully it might help 😄

**Comment by gminova** [comment]
Yes Lucy you Goddess!! thank you!

**Comment by xIrusux** [comment]
Hi lucy :) 

Thank you for your help. Reading your tip together with a bit of googling made me understand what to do yesterday. 

It works now yay! 

Happy Friday
